# `pre-commit` allows you to maintain consistent codebase by settng
# up rules to run your project against.
#
# While essentally a framework, t does support multiple languages through
# the use of hooks. Hooks are scripts that run against your codebase.
#
# Before modifying this file, ensure that you have opened a discussion around
# why a new hook is need as could cause breakage project-wide. Please do so by opening an
# issue on Github.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: "^$"
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: requirements-txt-fixer
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
    repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "88"]
        additional_dependencies: ["flake8-bugbear"]
        files: \.(py)$
        exclude: ^tests/
        types: [python]
        entry: flake8
        language: system
        stages: [commit]
        always_run: true
        verbose: true
        pass_filenames: false
        require_serial: true
        description: "Check for style and PEP8 issues"
        language_version: python3
        minimum_pre_commit_version: 0.0.0
        additional_dependencies: []
    repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

