# READ ME FIRST!
#
# ATTENTION: This file is used to build the docker image and run the container in production mode
#           It is not used to run the application in development mode
#           For development mode, see the README.md file on how to run the application using the Makefile
#
#

version: "3.9"

services:
  ## Paycheck Core Service
  paycheck-core-db:
    image: postgres:13-alpine
    container_name: paycheck-core-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  ## Paycheck Payments Service
  paycheck-payments-db:
    image: postgres:13-alpine
    container_name: paycheck-payments-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - paymentsdata-node:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  ## Paycheck Cards Service
  paycheck-cards-db:
    image: postgres:13-alpine
    container_name: paycheck-cards-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - cardsdata-node:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  ## Paycheck Test Database
  ## This is used to run the tests for the entire application
  testdb:
    image: postgres:13-alpine
    container_name: paycheck-test-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - testdata:/var/lib/postgresql/data
    profiles:
      - test
