#  Environment variables
#  ####################################################################################################
#  # READ ME FIRST!
#  #
#  # ATTENTION: This file is used to build the docker image and run the container in development mode
#
# #           For guide on how to run the application in development mode, see the README.md file
# #
# ####################################################################################################

services:
  paycheck_db:
    image: paycheck-core-db-dev:latest
    container_name:  paycheeck_dev_db
    context: backend/paycheck/docker
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - paycheck_dev_db:/var/lib/


volumes:
  paycheck_db:
